import type { Metadata } from "next";
import { Noto_Nastaliq_Urdu } from "next/font/google";
import clsx from "clsx";
import NextTopLoader from "nextjs-toploader";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Noto_Nastaliq_Urdu({
  variable: "--font-nastaliq",
  subsets: ["arabic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(font.variable, "antialiased")}>
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
