import clsx from "clsx";
import { Suspense } from "react";

import type { Metadata } from "next";
import { Noto_Nastaliq_Urdu } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import PatchLocationHash from "@/components/PatchLocationHash";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Noto_Nastaliq_Urdu({
  variable: "--font-nastaliq",
  subsets: ["arabic"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={clsx(font.variable, "h-full antialiased")}>
        <NuqsAdapter>
          <NextTopLoader />
          <Suspense fallback={null}>
            <PatchLocationHash />
          </Suspense>
          {children}
        </NuqsAdapter>

        <footer className="max-w-container mx-auto mt-32 w-full px-4 sm:px-6 lg:px-8" aria-labelledby="footer-heading">
          <h2 id="footer-heading" className="sr-only">
            Footer
          </h2>
          <div className="items-centers grid grid-cols-1 justify-between gap-4 border-t border-gray-100 py-6 md:grid-cols-2">
            <div />
            <div className="flex items-center px-4 justify-center space-x-4 text-sm/6 font-semibold text-slate-900 md:justify-end">
              <a target="_blank" href="https://github.com/nmanumr/allama-iqbal.com">Source Code</a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
